# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:

  server:
    container_name: patient-service
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - GRPC_SERVER_ADDRESS=billing-service
      - GRPC_SERVER_PORT=9001
      - SERVER_PORT=4000
    env_file:
      - .env.local

    ports:
      - 4000:4000
      - 9000:9000

  db:
    container_name: patient-service-db
    image: postgres
    restart: unless-stopped
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env.local
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready","-U","$DB_USERNAME","-d","$DB_DATABASE" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${DB_PORT}:5432
volumes:
  db-data:

