server:
  port: ${SERVER_PORT:4002}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/analytics-service}
spring:
  application:
    name: analytics-service

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Use ByteArrayDeserializer for value to receive raw bytes with protobuf
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      # Spring connect to Kafka inside Docker cotainer will resolve to 'broker:9092'
      # For local development use 'localhost:29092' with port mapping in docker-compose.yaml
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
      group-id: analytics-service
